-- =========================================================
-- Supabase schema for school service
-- Order:
-- 1) extensions and enums
-- 2) tables
-- 3) helper functions and triggers
-- 4) RLS and grants
-- 5) optional seed data
-- =========================================================

-- =========================================================
-- 1) Extensions
-- =========================================================
create extension if not exists pgcrypto;

-- =========================================================
-- 2) Enum Types
-- =========================================================
do $$ begin
  create type public.user_role as enum (
    'student',
    'teacher',
    'president',
    'vice_president',
    'admin'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.poll_status as enum (
    'draft',
    'active',
    'closed'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.point_type as enum (
    'sticker',
    'reward',
    'penalty'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.audit_action_type as enum (
    'create',
    'update',
    'delete',
    'role_change'
  );
exception
  when duplicate_object then null;
end $$;

-- =========================================================
-- 3) Tables
-- =========================================================

create table if not exists public.allowed_email_domains (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  school_email text not null unique,
  name text not null,
  role public.user_role not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notices (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_posts (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  headcount integer not null check (headcount > 0),
  location text not null,
  classroom_link text,
  military_service_available boolean not null default false,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.polls (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  allow_multiple boolean not null default false,
  is_anonymous boolean not null default false,
  status public.poll_status not null default 'draft',
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.poll_options (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  option_text text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_poll_options_poll_id_sort_order
on public.poll_options (poll_id, sort_order);

create table if not exists public.poll_votes (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  voter_user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (poll_id, voter_user_id)
);

create index if not exists idx_poll_votes_poll_id
on public.poll_votes (poll_id);

create index if not exists idx_poll_votes_voter_user_id
on public.poll_votes (voter_user_id);

create table if not exists public.poll_vote_items (
  id uuid primary key default gen_random_uuid(),
  vote_id uuid not null references public.poll_votes(id) on delete cascade,
  option_id uuid not null references public.poll_options(id) on delete cascade,
  unique (vote_id, option_id)
);

create index if not exists idx_poll_vote_items_vote_id
on public.poll_vote_items (vote_id);

create index if not exists idx_poll_vote_items_option_id
on public.poll_vote_items (option_id);

create table if not exists public.portfolios (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  file_path text not null,
  file_name text not null,
  file_size bigint not null check (file_size > 0),
  mime_type text not null,
  uploaded_at timestamptz not null default now()
);

create index if not exists idx_portfolios_user_id
on public.portfolios (user_id);

create table if not exists public.portfolio_feedbacks (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete restrict,
  feedback_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_portfolio_feedbacks_portfolio_id
on public.portfolio_feedbacks (portfolio_id);

create index if not exists idx_portfolio_feedbacks_teacher_id
on public.portfolio_feedbacks (teacher_id);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid not null references public.profiles(id) on delete restrict,
  action_type public.audit_action_type not null,
  target_table text not null,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_actor_id
on public.audit_logs (actor_id);

create index if not exists idx_audit_logs_target_table_target_id
on public.audit_logs (target_table, target_id);

create index if not exists idx_audit_logs_created_at
on public.audit_logs (created_at);

create table if not exists public.class_point_records (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete restrict,
  point_type public.point_type not null,
  point_value integer not null check (point_value > 0),
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create index if not exists idx_class_point_records_student_id
on public.class_point_records (student_id);

create index if not exists idx_class_point_records_teacher_id
on public.class_point_records (teacher_id);

create index if not exists idx_class_point_records_created_at
on public.class_point_records (created_at);

create table if not exists public.class_point_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  record_id uuid not null references public.class_point_records(id) on delete cascade,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_class_point_notifications_user_id
on public.class_point_notifications (user_id);

create index if not exists idx_class_point_notifications_record_id
on public.class_point_notifications (record_id);

-- =========================================================
-- 4) Helper Functions
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
$$;

create or replace function public.is_school_admin_role()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_user_role() in (
      'teacher'::public.user_role,
      'president'::public.user_role,
      'vice_president'::public.user_role,
      'admin'::public.user_role
    ),
    false
  )
$$;

create or replace function public.is_teacher_or_admin_role()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_user_role() in (
      'teacher'::public.user_role,
      'admin'::public.user_role
    ),
    false
  )
$$;

create or replace function public.validate_school_email(p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_local_part text;
  v_domain_part text;
  v_domain_exists boolean;
begin
  if v_email = '' then
    raise exception 'school email is required';
  end if;

  if position('@' in v_email) = 0 then
    raise exception 'invalid email format';
  end if;

  v_local_part := split_part(v_email, '@', 1);
  v_domain_part := split_part(v_email, '@', 2);

  select exists (
    select 1
    from public.allowed_email_domains d
    where d.domain = v_domain_part
      and d.is_active = true
  )
  into v_domain_exists;

  if not v_domain_exists then
    raise exception 'Only @e-mirim.hs.kr emails are allowed';
  end if;

  if v_local_part !~ '^s[0-9]{2}-(?:[1-9]|[1-6][0-9]|7[0-2])$' then
    raise exception 'Email local part must match sYY-1 to sYY-72 format';
  end if;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
  v_name text;
begin
  v_email := lower(trim(new.email));

  perform public.validate_school_email(v_email);

  v_name := coalesce(
    nullif(trim(new.raw_user_meta_data->>'name'), ''),
    nullif(trim(new.raw_user_meta_data->>'full_name'), ''),
    split_part(v_email, '@', 1)
  );

  insert into public.profiles (
    id,
    school_email,
    name,
    role
  )
  values (
    new.id,
    v_email,
    v_name,
    'student'::public.user_role
  );

  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_notices_updated_at on public.notices;
create trigger trg_notices_updated_at
before update on public.notices
for each row execute function public.set_updated_at();

drop trigger if exists trg_recruitment_posts_updated_at on public.recruitment_posts;
create trigger trg_recruitment_posts_updated_at
before update on public.recruitment_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_class_point_records_updated_at on public.class_point_records;
create trigger trg_class_point_records_updated_at
before update on public.class_point_records
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- 5) RLS + Grants
-- =========================================================

alter table public.allowed_email_domains enable row level security;
alter table public.profiles enable row level security;
alter table public.notices enable row level security;
alter table public.recruitment_posts enable row level security;
alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;
alter table public.poll_vote_items enable row level security;
alter table public.portfolios enable row level security;
alter table public.portfolio_feedbacks enable row level security;
alter table public.audit_logs enable row level security;
alter table public.class_point_records enable row level security;
alter table public.class_point_notifications enable row level security;

grant usage on schema public to authenticated;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.notices to authenticated;
grant select, insert, update, delete on public.recruitment_posts to authenticated;
grant select, insert, update, delete on public.polls to authenticated;
grant select, insert, update, delete on public.poll_options to authenticated;
grant select, insert, update, delete on public.poll_votes to authenticated;
grant select, insert, update, delete on public.poll_vote_items to authenticated;
grant select, insert, update, delete on public.portfolios to authenticated;
grant select, insert, update, delete on public.portfolio_feedbacks to authenticated;
grant select, insert, update, delete on public.allowed_email_domains to authenticated;
grant select, insert, update, delete on public.audit_logs to authenticated;
grant select, insert, update, delete on public.class_point_records to authenticated;
grant select, insert, update, delete on public.class_point_notifications to authenticated;

drop policy if exists profiles_select_own_or_staff on public.profiles;
create policy profiles_select_own_or_staff
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.is_school_admin_role()
);

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin
on public.profiles
for update
to authenticated
using (
  id = auth.uid()
  or public.current_user_role() = 'admin'::public.user_role
)
with check (
  id = auth.uid()
  or public.current_user_role() = 'admin'::public.user_role
);

drop policy if exists allowed_email_domains_admin_only on public.allowed_email_domains;
create policy allowed_email_domains_admin_only
on public.allowed_email_domains
for all
to authenticated
using (
  public.current_user_role() = 'admin'::public.user_role
)
with check (
  public.current_user_role() = 'admin'::public.user_role
);

drop policy if exists notices_select_members on public.notices;
create policy notices_select_members
on public.notices
for select
to authenticated
using (
  auth.uid() is not null
);

drop policy if exists notices_write_staff on public.notices;
create policy notices_write_staff
on public.notices
for insert
to authenticated
with check (
  public.is_school_admin_role()
);

drop policy if exists notices_update_staff on public.notices;
create policy notices_update_staff
on public.notices
for update
to authenticated
using (
  public.is_school_admin_role()
)
with check (
  public.is_school_admin_role()
);

drop policy if exists notices_delete_staff on public.notices;
create policy notices_delete_staff
on public.notices
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists recruitment_posts_select_members on public.recruitment_posts;
create policy recruitment_posts_select_members
on public.recruitment_posts
for select
to authenticated
using (
  auth.uid() is not null
);

drop policy if exists recruitment_posts_write_staff on public.recruitment_posts;
create policy recruitment_posts_write_staff
on public.recruitment_posts
for insert
to authenticated
with check (
  public.is_school_admin_role()
);

drop policy if exists recruitment_posts_update_staff on public.recruitment_posts;
create policy recruitment_posts_update_staff
on public.recruitment_posts
for update
to authenticated
using (
  public.is_school_admin_role()
)
with check (
  public.is_school_admin_role()
);

drop policy if exists recruitment_posts_delete_staff on public.recruitment_posts;
create policy recruitment_posts_delete_staff
on public.recruitment_posts
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists polls_select_visible on public.polls;
create policy polls_select_visible
on public.polls
for select
to authenticated
using (
  status in ('active', 'closed')
  or created_by = auth.uid()
  or public.is_school_admin_role()
);

drop policy if exists polls_write_staff on public.polls;
create policy polls_write_staff
on public.polls
for insert
to authenticated
with check (
  public.is_school_admin_role()
);

drop policy if exists polls_update_staff on public.polls;
create policy polls_update_staff
on public.polls
for update
to authenticated
using (
  public.is_school_admin_role()
)
with check (
  public.is_school_admin_role()
);

drop policy if exists polls_delete_staff on public.polls;
create policy polls_delete_staff
on public.polls
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists poll_options_select_visible on public.poll_options;
create policy poll_options_select_visible
on public.poll_options
for select
to authenticated
using (
  exists (
    select 1
    from public.polls p
    where p.id = poll_id
      and (
        p.status in ('active', 'closed')
        or p.created_by = auth.uid()
        or public.is_school_admin_role()
      )
  )
);

drop policy if exists poll_options_write_staff on public.poll_options;
create policy poll_options_write_staff
on public.poll_options
for insert
to authenticated
with check (
  public.is_school_admin_role()
);

drop policy if exists poll_options_update_staff on public.poll_options;
create policy poll_options_update_staff
on public.poll_options
for update
to authenticated
using (
  public.is_school_admin_role()
)
with check (
  public.is_school_admin_role()
);

drop policy if exists poll_options_delete_staff on public.poll_options;
create policy poll_options_delete_staff
on public.poll_options
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists poll_votes_select_own_or_staff on public.poll_votes;
create policy poll_votes_select_own_or_staff
on public.poll_votes
for select
to authenticated
using (
  voter_user_id = auth.uid()
  or public.is_school_admin_role()
);

drop policy if exists poll_votes_insert_own_active on public.poll_votes;
create policy poll_votes_insert_own_active
on public.poll_votes
for insert
to authenticated
with check (
  voter_user_id = auth.uid()
  and exists (
    select 1
    from public.polls p
    where p.id = poll_id
      and p.status = 'active'
  )
);

drop policy if exists poll_votes_delete_staff on public.poll_votes;
create policy poll_votes_delete_staff
on public.poll_votes
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists poll_vote_items_select_own_or_staff on public.poll_vote_items;
create policy poll_vote_items_select_own_or_staff
on public.poll_vote_items
for select
to authenticated
using (
  exists (
    select 1
    from public.poll_votes v
    where v.id = vote_id
      and (
        v.voter_user_id = auth.uid()
        or public.is_school_admin_role()
      )
  )
);

drop policy if exists poll_vote_items_insert_own_active on public.poll_vote_items;
create policy poll_vote_items_insert_own_active
on public.poll_vote_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.poll_votes v
    join public.polls p
      on p.id = v.poll_id
    join public.poll_options o
      on o.id = option_id
     and o.poll_id = p.id
    where v.id = vote_id
      and v.voter_user_id = auth.uid()
      and p.status = 'active'
  )
);

drop policy if exists poll_vote_items_delete_staff on public.poll_vote_items;
create policy poll_vote_items_delete_staff
on public.poll_vote_items
for delete
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists portfolios_select_own_or_teacher on public.portfolios;
create policy portfolios_select_own_or_teacher
on public.portfolios
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_teacher_or_admin_role()
);

drop policy if exists portfolios_insert_own on public.portfolios;
create policy portfolios_insert_own
on public.portfolios
for insert
to authenticated
with check (
  user_id = auth.uid()
);

drop policy if exists portfolios_update_own on public.portfolios;
create policy portfolios_update_own
on public.portfolios
for update
to authenticated
using (
  user_id = auth.uid()
)
with check (
  user_id = auth.uid()
);

drop policy if exists portfolios_delete_own on public.portfolios;
create policy portfolios_delete_own
on public.portfolios
for delete
to authenticated
using (
  user_id = auth.uid()
);

drop policy if exists portfolio_feedbacks_select_own_or_teacher on public.portfolio_feedbacks;
create policy portfolio_feedbacks_select_own_or_teacher
on public.portfolio_feedbacks
for select
to authenticated
using (
  public.is_teacher_or_admin_role()
  or exists (
    select 1
    from public.portfolios p
    where p.id = portfolio_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists portfolio_feedbacks_insert_teacher on public.portfolio_feedbacks;
create policy portfolio_feedbacks_insert_teacher
on public.portfolio_feedbacks
for insert
to authenticated
with check (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists portfolio_feedbacks_update_teacher on public.portfolio_feedbacks;
create policy portfolio_feedbacks_update_teacher
on public.portfolio_feedbacks
for update
to authenticated
using (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
)
with check (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists portfolio_feedbacks_delete_teacher on public.portfolio_feedbacks;
create policy portfolio_feedbacks_delete_teacher
on public.portfolio_feedbacks
for delete
to authenticated
using (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists audit_logs_admin_only on public.audit_logs;
create policy audit_logs_admin_only
on public.audit_logs
for select
to authenticated
using (
  public.current_user_role() = 'admin'::public.user_role
);

drop policy if exists class_point_records_select_own_or_staff on public.class_point_records;
create policy class_point_records_select_own_or_staff
on public.class_point_records
for select
to authenticated
using (
  student_id = auth.uid()
  or public.is_teacher_or_admin_role()
);

drop policy if exists class_point_records_insert_staff on public.class_point_records;
create policy class_point_records_insert_staff
on public.class_point_records
for insert
to authenticated
with check (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists class_point_records_update_staff on public.class_point_records;
create policy class_point_records_update_staff
on public.class_point_records
for update
to authenticated
using (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
)
with check (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists class_point_records_delete_staff on public.class_point_records;
create policy class_point_records_delete_staff
on public.class_point_records
for delete
to authenticated
using (
  teacher_id = auth.uid()
  and public.is_teacher_or_admin_role()
);

drop policy if exists class_point_notifications_select_own_or_staff on public.class_point_notifications;
create policy class_point_notifications_select_own_or_staff
on public.class_point_notifications
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_teacher_or_admin_role()
);

drop policy if exists class_point_notifications_insert_staff on public.class_point_notifications;
create policy class_point_notifications_insert_staff
on public.class_point_notifications
for insert
to authenticated
with check (
  public.is_teacher_or_admin_role()
);

drop policy if exists class_point_notifications_update_own_or_staff on public.class_point_notifications;
create policy class_point_notifications_update_own_or_staff
on public.class_point_notifications
for update
to authenticated
using (
  user_id = auth.uid()
  or public.is_teacher_or_admin_role()
)
with check (
  user_id = auth.uid()
  or public.is_teacher_or_admin_role()
);

drop policy if exists class_point_notifications_delete_staff on public.class_point_notifications;
create policy class_point_notifications_delete_staff
on public.class_point_notifications
for delete
to authenticated
using (
  public.is_teacher_or_admin_role()
);

-- =========================================================
-- 6) Optional seed data
-- =========================================================

insert into public.allowed_email_domains (domain, is_active)
values ('e-mirim.hs.kr', true)
on conflict (domain) do update
set is_active = excluded.is_active;

-- Sample rows below need existing auth.users rows first.
-- Replace the UUIDs with real auth.users.id values before running.
do $$
declare
  v_teacher_id uuid := '11111111-1111-1111-1111-111111111111';
  v_president_id uuid := '22222222-2222-2222-2222-222222222222';
  v_student_id uuid := '33333333-3333-3333-3333-333333333333';

  v_poll_id uuid;
  v_option_1 uuid;
  v_portfolio_id uuid;
begin
  if exists (select 1 from auth.users where id = v_teacher_id)
     and not exists (select 1 from public.profiles where id = v_teacher_id) then
    insert into public.profiles (id, school_email, name, role)
    values (v_teacher_id, 'teacher@e-mirim.hs.kr', '담임교사', 'teacher');
  end if;

  if exists (select 1 from auth.users where id = v_president_id)
     and not exists (select 1 from public.profiles where id = v_president_id) then
    insert into public.profiles (id, school_email, name, role)
    values (v_president_id, 's25-1@e-mirim.hs.kr', '회장학생', 'president');
  end if;

  if exists (select 1 from auth.users where id = v_student_id)
     and not exists (select 1 from public.profiles where id = v_student_id) then
    insert into public.profiles (id, school_email, name, role)
    values (v_student_id, 's25-2@e-mirim.hs.kr', '학생A', 'student');
  end if;

  if exists (select 1 from public.profiles where id = v_teacher_id) then
    insert into public.notices (title, content, created_by)
    values (
      '공지사항 테스트',
      'Supabase 공지사항 샘플 데이터입니다.',
      v_teacher_id
    );
  end if;

  if exists (select 1 from public.profiles where id = v_teacher_id) then
    insert into public.recruitment_posts (
      company_name,
      headcount,
      location,
      classroom_link,
      military_service_available,
      created_by
    )
    values (
      '미림소프트',
      3,
      '서울시 강남구',
      'https://classroom.google.com/c/test-link',
      true,
      v_teacher_id
    );
  end if;

  if exists (select 1 from public.profiles where id = v_president_id) then
    insert into public.polls (
      title,
      allow_multiple,
      is_anonymous,
      status,
      created_by
    )
    values (
      '다음 체육대회 종목 투표',
      false,
      true,
      'active',
      v_president_id
    )
    returning id into v_poll_id;

    insert into public.poll_options (poll_id, option_text, sort_order)
    values (v_poll_id, '축구', 1)
    returning id into v_option_1;

    insert into public.poll_options (poll_id, option_text, sort_order)
    values (v_poll_id, '피구', 2);
  end if;

  if exists (select 1 from public.profiles where id = v_student_id)
     and v_poll_id is not null then
    insert into public.poll_votes (poll_id, voter_user_id)
    values (v_poll_id, v_student_id);

    insert into public.poll_vote_items (vote_id, option_id)
    select pv.id, v_option_1
    from public.poll_votes pv
    where pv.poll_id = v_poll_id
      and pv.voter_user_id = v_student_id;
  end if;

  if exists (select 1 from public.profiles where id = v_student_id) then
    insert into public.portfolios (
      user_id,
      file_path,
      file_name,
      file_size,
      mime_type
    )
    values (
      v_student_id,
      'portfolios/sample-portfolio.pdf',
      'sample-portfolio.pdf',
      12582912,
      'application/pdf'
    )
    returning id into v_portfolio_id;
  end if;

  if exists (select 1 from public.profiles where id = v_teacher_id)
     and v_portfolio_id is not null then
    insert into public.portfolio_feedbacks (
      portfolio_id,
      teacher_id,
      feedback_text
    )
    values (
      v_portfolio_id,
      v_teacher_id,
      '포트폴리오 구성이 깔끔하고 프로젝트 설명이 좋아요. 다음에는 결과 지표를 조금 더 넣으면 더 좋아집니다.'
    );
  end if;
end $$;

-- =========================================================
-- Google Classroom 연동용 최소 DB 수정
-- =========================================================

-- =========================================================
-- 1) Extensions
-- =========================================================
create extension if not exists pgcrypto;

-- =========================================================
-- 2) Enum Types
-- =========================================================
do $$ begin
  create type public.classroom_post_type as enum (
    'announcement',
    'coursework',
    'material'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.classroom_parse_status as enum (
    'pending',
    'parsed_notice',
    'parsed_recruitment',
    'failed'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  alter type public.classroom_parse_status add value if not exists 'unknown';
exception
  when duplicate_object then null;
end $$;

do $$ begin
  alter type public.classroom_parse_status add value if not exists 'partial_recruitment';
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.content_source_type as enum (
    'manual',
    'classroom'
  );
exception
  when duplicate_object then null;
end $$;

-- =========================================================
-- 3) Tables
-- =========================================================

create table if not exists public.classroom_raw_posts (
  id uuid primary key default gen_random_uuid(),
  course_id text not null,
  course_name text not null,
  classroom_post_id text not null,
  post_type public.classroom_post_type not null,
  title text,
  content text,
  teacher_name text,
  due_at timestamptz,
  max_points numeric(10,2),
  raw_json jsonb not null default '{}'::jsonb,
  parse_status public.classroom_parse_status not null default 'pending',
  linked_notice_id uuid null references public.notices(id) on delete set null,
  linked_recruitment_post_id uuid null references public.recruitment_posts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, classroom_post_id)
);

create index if not exists idx_classroom_raw_posts_course_id
on public.classroom_raw_posts (course_id);

create index if not exists idx_classroom_raw_posts_classroom_post_id
on public.classroom_raw_posts (classroom_post_id);

create index if not exists idx_classroom_raw_posts_post_type
on public.classroom_raw_posts (post_type);

create index if not exists idx_classroom_raw_posts_parse_status
on public.classroom_raw_posts (parse_status);

create index if not exists idx_classroom_raw_posts_created_at
on public.classroom_raw_posts (created_at);

alter table public.classroom_raw_posts
  enable row level security;

alter table public.notices
  add column if not exists source_type public.content_source_type not null default 'manual';

alter table public.notices
  add column if not exists classroom_raw_post_id uuid null references public.classroom_raw_posts(id) on delete set null;

do $$ begin
  alter table public.notices
    add constraint notices_classroom_raw_post_id_unique unique (classroom_raw_post_id);
exception
  when duplicate_object then null;
end $$;

create index if not exists idx_notices_source_type
on public.notices (source_type);

create index if not exists idx_notices_classroom_raw_post_id
on public.notices (classroom_raw_post_id);

alter table public.recruitment_posts
  add column if not exists business_registration_number text;

alter table public.recruitment_posts
  add column if not exists industry text;

alter table public.recruitment_posts
  add column if not exists employee_count integer check (employee_count > 0);

alter table public.recruitment_posts
  add column if not exists revenue_scale text;

alter table public.recruitment_posts
  add column if not exists address text;

alter table public.recruitment_posts
  add column if not exists website_url text;

alter table public.recruitment_posts
  add column if not exists job_description text;

alter table public.recruitment_posts
  add column if not exists requirements text;

alter table public.recruitment_posts
  add column if not exists recommendation_target text;

alter table public.recruitment_posts
  add column if not exists document_deadline timestamptz;

alter table public.recruitment_posts
  add column if not exists benefits text;

alter table public.recruitment_posts
  add column if not exists source_type public.content_source_type not null default 'manual';

alter table public.recruitment_posts
  add column if not exists classroom_raw_post_id uuid null references public.classroom_raw_posts(id) on delete set null;

do $$ begin
  alter table public.recruitment_posts
    add constraint recruitment_posts_classroom_raw_post_id_unique unique (classroom_raw_post_id);
exception
  when duplicate_object then null;
end $$;

create index if not exists idx_recruitment_posts_source_type
on public.recruitment_posts (source_type);

create index if not exists idx_recruitment_posts_classroom_raw_post_id
on public.recruitment_posts (classroom_raw_post_id);

create index if not exists idx_recruitment_posts_document_deadline
on public.recruitment_posts (document_deadline);

-- =========================================================
-- 4) Helper Functions / Triggers
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_classroom_raw_posts_updated_at on public.classroom_raw_posts;
create trigger trg_classroom_raw_posts_updated_at
before update on public.classroom_raw_posts
for each row execute function public.set_updated_at();

-- =========================================================
-- 5) RLS + Grants
-- =========================================================

grant select, insert, update, delete on public.classroom_raw_posts to authenticated;

drop policy if exists classroom_raw_posts_select_staff on public.classroom_raw_posts;
create policy classroom_raw_posts_select_staff
on public.classroom_raw_posts
for select
to authenticated
using (
  public.is_school_admin_role()
);

drop policy if exists classroom_raw_posts_write_staff on public.classroom_raw_posts;
create policy classroom_raw_posts_write_staff
on public.classroom_raw_posts
for insert
to authenticated
with check (
  public.is_school_admin_role()
);

drop policy if exists classroom_raw_posts_update_staff on public.classroom_raw_posts;
create policy classroom_raw_posts_update_staff
on public.classroom_raw_posts
for update
to authenticated
using (
  public.is_school_admin_role()
)
with check (
  public.is_school_admin_role()
);

drop policy if exists classroom_raw_posts_delete_staff on public.classroom_raw_posts;
create policy classroom_raw_posts_delete_staff
on public.classroom_raw_posts
for delete
to authenticated
using (
  public.is_school_admin_role()
);
